sudo: false

language:
  - php
  - node_js

php:
  - 5.2
  - 5.4

node_js:
  - 0.10

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=1

before_script:
  - export DEV_LIB_PATH=dev-lib
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - source $DEV_LIB_PATH/travis.before_script.sh

script:
  - $DEV_LIB_PATH/travis.script.sh

after_script:
  - $DEV_LIB_PATH/travis.after_script.sh

notifications:
  slack:
    secure: piVKmEr6QHaLnun/iZFy2iPI0s7gyvFO8zb8xFPtmv9hRgyZ339+DhC5KKjNAKEHBa4Kho44Ta6l3Sz45Nc2aa22H0AWPTAgVfhaY5an6vdwXry6TdzdshC/DlFbglAp0wmokK+E4jS9zb+Y0LNL3Yi1RnkC4DKYtu8iF8iwfNA=