sudo: false

language:
  - php

include:
  - php: 5.2
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: hhvm
  - php: nightly

allow_failures:
  - php: hhvm
  - php: nightly

fast_finish: true

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=1

before_install:
  - git clone https://github.com/woothemes/woocommerce.git /tmp/wordpress/wp-content/plugins/woocommerce

before_script:
  - export DEV_LIB_PATH=tools
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - source $DEV_LIB_PATH/travis.before_script.sh

script:
  - $DEV_LIB_PATH/travis.script.sh

after_script:
  - $DEV_LIB_PATH/travis.after_script.sh

notifications:
  slack:
    secure: YFHfchJXLsV5AQcpkXQ6j+BeLicPgwWMSh1mIxgosYyw7DR23IHwNqyX56aLeNs13b9NJL1rE1qO1x78i2uxfPoCTI6la+wwyb0iyAV8RuX6LaCVHhyW0I/Y0bRFzvPdo0b0oTFiWxK7ZXFPh8GJNcwhCppWJPEngGauSHZQdwE=
