sudo: false

language: php

php:
    - 5.2
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=trunk WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=1

install:
    - export DEV_LIB_PATH=dev-lib
    - export THEME_GIT_PLUGIN_DEPENDENCIES=https://github.com/woothemes/woocommerce.git,https://github.com/woothemes/subscribe-and-connect.git
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh

notifications:
    slack:
        secure: YFHfchJXLsV5AQcpkXQ6j+BeLicPgwWMSh1mIxgosYyw7DR23IHwNqyX56aLeNs13b9NJL1rE1qO1x78i2uxfPoCTI6la+wwyb0iyAV8RuX6LaCVHhyW0I/Y0bRFzvPdo0b0oTFiWxK7ZXFPh8GJNcwhCppWJPEngGauSHZQdwE=
